In [1]:
import numpy as np

a = np.array([1, 2, 3, 4])
b = np.array([[1,2,3],[4,5,6]])
print("1D array:", a)
print("2D array:\n", b)

print(b.shape)
print(b.ndim)
print(b.size)

1D array: [1 2 3 4]
2D array:
 [[1 2 3]
 [4 5 6]]
(2, 3)
2
6


In [2]:
import numpy as np

a = np.zeros((2,2))   # Create an array of all zeros
print(a)              # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"

b = np.ones((1,2))    # Create an array of all ones
print(b)              # Prints "[[ 1.  1.]]"

c = np.full((2,2), 7)  # Create a constant array
print(c)               # Prints "[[ 7.  7.]
                       #          [ 7.  7.]]"

d = np.eye(2)         # Create a 2x2 identity matrix
print(d)              # Prints "[[ 1.  0.]
                      #          [ 0.  1.]]"

e = np.random.random((2,2))  # Create an array filled with random values
print(e)                     # Might print "[[ 0.91940167  0.08143941]
                             #               [ 0.68744134  0.87236687]]"

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.3623103  0.55038883]
 [0.43928211 0.64365464]]


In [4]:
import numpy as np

arr = np.array([[[1,2,3,4,5], [6,7,8,9,10]]])
print(arr[0][1][1])
arr = np.array([[[1,2,3,4,5], [6,7,8,9,10]]])
print(arr[0][0:3])


7
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [5]:
import numpy as np

arr = np.array([1.1,2.1,3.1])
newarr = arr.astype("i")
print(newarr)
newarr = arr.astype("bool")
print(newarr)

[1 2 3]
[ True  True  True]


In [6]:
import numpy as np

arr = np.array([10.50,0,50])
newarr = arr.astype("i")
print(newarr)
newarr = arr.astype("bool")
print(newarr)

[10  0 50]
[ True False  True]


In [8]:
import numpy as np
arr = np.array([1,2,3,4],ndmin=5)

print(arr)
print('shape of array',arr.shape)

[[[[[1 2 3 4]]]]]
shape of array (1, 1, 1, 1, 4)


In [9]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(4,3)
newarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [11]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
for x in arr :
    for y in x :
        print (y)

1
2
3
4
5
6


In [20]:
import numpy as np 
arr = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8
